<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml [
<!ELEMENT xml (OrgQuestion*)>
<!ATTLIST xml 
version CDATA #REQUIRED
>
<!ELEMENT OrgQuestion (OrgQSubject, OrgQBody, Thread)>
<!ATTLIST OrgQuestion 
ORGQ_ID CDATA #REQUIRED
>
<!ELEMENT OrgQSubject (#PCDATA)>
<!ELEMENT OrgQBody (#PCDATA)>
<!ELEMENT Thread (RelQuestion, RelComment*)>
<!ATTLIST Thread
 THREAD_SEQUENCE CDATA #REQUIRED
 SubtaskA_Skip_Because_Same_As_RelQuestion_ID CDATA #IMPLIED
>
<!ELEMENT RelQuestion (RelQSubject, RelQBody)>
<!ATTLIST RelQuestion
RELQ_ID CDATA #REQUIRED
RELQ_RANKING_ORDER CDATA #REQUIRED
RELQ_CATEGORY CDATA #REQUIRED
RELQ_DATE CDATA #REQUIRED
RELQ_USERID CDATA #REQUIRED
RELQ_USERNAME CDATA #REQUIRED
RELQ_RELEVANCE2ORGQ CDATA #REQUIRED
>
<!ELEMENT RelQSubject (#PCDATA)>
<!ELEMENT RelQBody (#PCDATA)>
<!ELEMENT RelComment (RelCText)>
<!ATTLIST RelComment
RELC_ID CDATA #REQUIRED
RELC_DATE CDATA #REQUIRED
RELC_USERID CDATA #REQUIRED
RELC_USERNAME CDATA #REQUIRED
RELC_RELEVANCE2ORGQ CDATA #REQUIRED
RELC_RELEVANCE2RELQ CDATA #REQUIRED
>
<!ELEMENT RelCText (#PCDATA)>
]>
<xml version="1.0">
<OrgQuestion ORGQ_ID="Q318">
	<OrgQSubject>"IT Jobs in Qatar</OrgQSubject>
	<OrgQBody>""how hard is it for you to get a decent paying job in qatar? I had applied in bayt;monstergulf and gulftalent almost religiously every day and yet I am getting nothing more than having my CV viewed. I have 4 years + experience in Linux and Unix environment and a handful of certifications to boot also. well; while its back to updating my CV; I'd love to hear about your experiences on getting a job here."""</OrgQBody>

	<Thread THREAD_SEQUENCE="Q318_R4" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q56_R4">
		<RelQuestion RELQ_ID="Q318_R4" RELQ_RANKING_ORDER="4" RELQ_CATEGORY="Opportunities" RELQ_DATE="2012-11-12 13:06:59" RELQ_USERID="U1929" RELQ_USERNAME="doha0303" RELQ_RELEVANCE2ORGQ="PerfectMatch">
			<RelQSubject>Why finding a job in Doha so hard?</RelQSubject>
			<RelQBody>Can somebody tell me how i get a good job in doha? i have an American passport and holding a husband visas; with a bachelor degree; speaking 3 languages; having a hard time to find a good job; i post my CV on many website including bayt.com and many more; but didn't get any respond. Thanks.</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q318_R4_C1" RELC_DATE="2012-11-12 13:39:04" RELC_USERID="U3" RELC_USERNAME="anonymous" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Are you Qatari? That may be the answer.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R4_C2" RELC_DATE="2012-11-12 13:41:33" RELC_USERID="U1929" RELC_USERNAME="doha0303" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>No I am not qatari; but I can speak Arabic; It's my second language..</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R4_C3" RELC_DATE="2012-11-12 13:42:08" RELC_USERID="U112" RELC_USERNAME="mimiloves2sing" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Not easy..... unless you have a father's rp or married to a man who has atleast 10;000r a month salary to be on his rp Getting interviews are easy with a nice Modern Key Words CV that features your accomplishments.... Getting a visa to work is the problem. I speak from 10 mos experience on this. Best wishes</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R4_C4" RELC_DATE="2012-11-12 13:43:57" RELC_USERID="U62" RELC_USERNAME="smoke" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Wasta my child...thats all it takes. Having American passport is of no use if jobs in your field can be filled with cheaper hires. comprende?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R4_C5" RELC_DATE="2012-11-12 13:46:33" RELC_USERID="U62" RELC_USERNAME="smoke" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>also as tahsinmim said..helps sometimes to hand over the CV directly. I think she's already on her husbands's sponsorship as she mentioned that.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R4_C6" RELC_DATE="2012-11-12 13:55:50" RELC_USERID="U1930" RELC_USERNAME="pixiequeen" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Good">
			<RelCText>QDClover I guess you are not a Qatari and you still have a job! So it’s not always true. Try visiting the recruitment companies in person. It helps.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R4_C7" RELC_DATE="2012-11-12 14:02:31" RELC_USERID="U1930" RELC_USERNAME="pixiequeen" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Smoke; International/govt/semi govt companies wont accept CV by hand.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R4_C8" RELC_DATE="2012-11-12 14:02:40" RELC_USERID="U1929" RELC_USERNAME="doha0303" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Yes i am on husband visas; and don't want to transfer my visas to the company that's why i think it's hard for me to get a job. Thanks to all.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R4_C9" RELC_DATE="2012-11-12 14:03:18" RELC_USERID="U3" RELC_USERNAME="anonymous" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>No; not Qatari but a good old Aussie. They offered me a job before I came but it does annoy me people complaining that they can't get a job in someone elses country. Is it easy for Qataris to get jobs in the US?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R4_C10" RELC_DATE="2012-11-12 14:04:49" RELC_USERID="U112" RELC_USERNAME="mimiloves2sing" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Kat yep very true about the type of work you are experienced in; if the position can be filled local the mindset is.....why hire a American that will want more salary then a different nationality? Wasta; I have but lol kat i dont have the right wasta so im out of here. even with a catchy; professional cv it all came down to wrong visa. lol and they say being American with upon arrival visa is transferable.... ya right.... Can u be my wasta? It is EASY if you are on husbands rp; just need patience as this is Qatar they move slow in HR; but they get over 100+ applications a day. IF your CV is eye catching and has what they need; you will get a call for interview.</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q318">
	<OrgQSubject>"IT Jobs in Qatar</OrgQSubject>
	<OrgQBody>""how hard is it for you to get a decent paying job in qatar? I had applied in bayt;monstergulf and gulftalent almost religiously every day and yet I am getting nothing more than having my CV viewed. I have 4 years + experience in Linux and Unix environment and a handful of certifications to boot also. well; while its back to updating my CV; I'd love to hear about your experiences on getting a job here."""</OrgQBody>

	<Thread THREAD_SEQUENCE="Q318_R6">
		<RelQuestion RELQ_ID="Q318_R6" RELQ_RANKING_ORDER="6" RELQ_CATEGORY="Opportunities" RELQ_DATE="2012-12-26 17:50:49" RELQ_USERID="U3" RELQ_USERNAME="anonymous" RELQ_RELEVANCE2ORGQ="PerfectMatch">
			<RelQSubject>IT Jobs in Qatar</RelQSubject>
			<RelQBody>how hard is it for you to get a decent paying job in qatar? I had applied in bayt;monstergulf and gulftalent almost religiously every day and yet I am getting nothing more than having my CV viewed. I have 4 years + experience in Linux and Unix environment and a handful of certifications to boot also. well; while its back to updating my CV; I'd love to hear about your experiences on getting a job here.</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q318_R6_C1" RELC_DATE="2012-12-26 18:28:16" RELC_USERID="U5529" RELC_USERNAME="baazir" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Ive been here for a month and getting nothing back like u. Finished BSc IT and Worked in a large comp in UK for 3 years. Having hundred of knowledge sectors and certificates but everything became useless before gulf experience. Beyond ad and job sites Im visiting to companies and created own portfolio web as well. Got 3 or 4 mails since advertised and just they got back my resume. Lets see Good Luck to u :)</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C2" RELC_DATE="2012-12-26 19:56:40" RELC_USERID="U5530" RELC_USERNAME="lailuen" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Good">
			<RelCText>seems like there are lot of job opportunities but nobody seems to get it... i hear people coming to work in Qatar everyday... but doesnt seems to be able to fing wokr myself</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C3" RELC_DATE="2012-12-26 22:03:05" RELC_USERID="U996" RELC_USERNAME="BlueBull" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Qatar is not the place for people with IT Experiencewho really want to make a career in IT. Qatar IT is desktop and network management only.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C4" RELC_DATE="2012-12-26 22:32:23" RELC_USERID="U5531" RELC_USERNAME="sandeepclt" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Good">
			<RelCText>i am here for last 1 month and not even called for a single interview. i have 8 yrs of IT exp and worked for one of the biggest MNC in India. looks like the decision to come here turning out to be wrong... bcoz i am confident on my skills; may go back back to india after searching for 1 more month :) i didn't get any guidance b4 coming. so pls come here if someone can get you a job... Sandy</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C5" RELC_DATE="2012-12-27 07:35:30" RELC_USERID="U5532" RELC_USERNAME="praveen06527" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Shall we talk about gulftalent...I think it is a wasiting of time...No positive response for me for the last three years from gulftalent.Now i stopped to login to that.better we go directly to the company career site.Expecting your valuable comments.thanks to all in advance.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C6" RELC_DATE="2012-12-27 11:18:28" RELC_USERID="U3" RELC_USERNAME="anonymous" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>how did u advertise your resume then? this place is kind of depressing isn't it?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C7" RELC_DATE="2012-12-27 12:53:02" RELC_USERID="U4100" RELC_USERNAME="Brad_cin_dell" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>On the same boat.. :-(</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C8" RELC_DATE="2012-12-27 15:04:25" RELC_USERID="U5533" RELC_USERNAME="shafcp" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>forward ur cv to admin@arablandgroup.com; let hope for the best</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C9" RELC_DATE="2012-12-27 15:50:53" RELC_USERID="U5534" RELC_USERNAME="Ahmad_Mansoor" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="Good">
			<RelCText>well maybe if there wasn't 1 billion of you guys trying to take the same job from those few companies. Yet the new generation is also going crazy enrolling in IT degrees... How many IT jobs you think there are in this place? Unix and Linux are jobs for men in here.. Yes believe me; certain jobs are dedicated for each gender... an IT company that needs a Unix admin; that is 99.99% male dominated department would NEVER hire a woman. Sorry to burst the bubble; reality is bitter Good luck try harder.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R6_C10" RELC_DATE="2012-12-27 16:16:18" RELC_USERID="U5535" RELC_USERNAME="Azhar89" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="Good">
			<RelCText>An IT job in the middle east; especially Qatar - Not a smart idea!</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q318">
	<OrgQSubject>"IT Jobs in Qatar</OrgQSubject>
	<OrgQBody>""how hard is it for you to get a decent paying job in qatar? I had applied in bayt;monstergulf and gulftalent almost religiously every day and yet I am getting nothing more than having my CV viewed. I have 4 years + experience in Linux and Unix environment and a handful of certifications to boot also. well; while its back to updating my CV; I'd love to hear about your experiences on getting a job here."""</OrgQBody>

	<Thread THREAD_SEQUENCE="Q318_R9" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q141_R52">
		<RelQuestion RELQ_ID="Q318_R9" RELQ_RANKING_ORDER="9" RELQ_CATEGORY="Opportunities" RELQ_DATE="2015-01-05 23:51:33" RELQ_USERID="U3612" RELQ_USERNAME="kumaresanm" RELQ_RELEVANCE2ORGQ="Relevant">
			<RelQSubject>Are Indians really getting job in Qatar right now?</RelQSubject>
			<RelQBody>I am coming to qatar in visit visa coming week to search for a job. I've got no reference as such. Applied in many sites in Qatar; Not even a single positive response. Finally; i am hearing these: 1. Work visa not given for Indians 2. Oil price has come down. Anyone please tell me if these reasons are valid and true? If So; how to actually get a job in Qatar? Your suggestions could help me and anybody who is dying to get a job in Qatar...</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q318_R9_C1" RELC_DATE="2015-01-06 07:42:19" RELC_USERID="U3613" RELC_USERNAME="kvpk1977" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>what kind of job are you looking for?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R9_C2" RELC_DATE="2015-01-06 07:48:41" RELC_USERID="U3612" RELC_USERNAME="kumaresanm" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>IT support</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R9_C3" RELC_DATE="2015-01-06 09:11:03" RELC_USERID="U3614" RELC_USERNAME="Master Mind" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Most of companies they haven't Indian visas to issuing.... if have you do not get these same profession. May be getting other category.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R9_C4" RELC_DATE="2015-01-06 09:56:14" RELC_USERID="U3615" RELC_USERNAME="GTA ASSOCIATES" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>There are many restrictions in Qatar apart from Indian Visas... family visa would always be an issue; what ever the profession you are ... biz policies are not friendly as UAE... rents are higher...</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R9_C5" RELC_DATE="2015-01-06 11:08:25" RELC_USERID="U3616" RELC_USERNAME="hussainvr.qatar" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Honestly; if you want job in Qatar within one month submit your resume by going directly to that office. don't wait for Email responses bcz every companies getting 100 of spam mails daily. Don't hesitate to follow up again if you didn't get reply yet.Post Ads in Gulf-time newspaper is important thing by mentioning INDIAN IT SUPPORT Engineer with your relevant exp and visa type. don't forget to post in Qatarliving. join in IT social communities; make list of companies from linkeIn; Bayt and Collect HR email and Employees Call them if you found vacancy; never mind.. if they will tell you 'bla bla bla' actually they doesn't know anything so; whatever it is .. go directly to the office ; submit CV; collect Business card and HR Email.make followup after 5 days. you must be prepared for any kind of interviews. This is a fact .. Every companies need Indian employees because they are Hard workers than others. profession may be vary but it doesn't matter if you will get all the benefits from th.....</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R9_C6" RELC_DATE="2015-01-06 11:18:06" RELC_USERID="U3617" RELC_USERNAME="coxtown" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Kumar; Well; you can come and take a chance; there are jobs available for Indians but as you said; it is not that easy or abundant. Still your luck and merit counts. Better try to stay for 3 months; in 1 month nothing will materialise unless you know some big shots to take care of you. But do not resign your current job. Hold on as standby. PS: Oil price coming down or LNG price going up etc.; nothing to do with Qatar; they are well stabilized for next 50 years. Good luck.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R9_C7" RELC_DATE="2015-01-06 18:03:39" RELC_USERID="U3495" RELC_USERNAME="Motiv8er" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>The responses really enlightened me... Thank you QL !</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R9_C8" RELC_DATE="2015-01-07 00:15:33" RELC_USERID="U3612" RELC_USERNAME="kumaresanm" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>@mastermind: in one of your posts; you have mentioned visa available for Indians. Is it work visa and for what type of job are you providing visa?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R9_C9" RELC_DATE="2015-01-07 00:18:43" RELC_USERID="U3612" RELC_USERNAME="kumaresanm" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Thanks everyone for your suggestions. Really appreciate them.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R9_C10" RELC_DATE="2015-01-07 18:04:02" RELC_USERID="U3618" RELC_USERNAME="farhanmyr" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>company look only those who are in the same country(90%) ;most of the Job Portal there is a condition like expatriates can only apply ; so better to come here and apply ; best of luck brother</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q318">
	<OrgQSubject>"IT Jobs in Qatar</OrgQSubject>
	<OrgQBody>""how hard is it for you to get a decent paying job in qatar? I had applied in bayt;monstergulf and gulftalent almost religiously every day and yet I am getting nothing more than having my CV viewed. I have 4 years + experience in Linux and Unix environment and a handful of certifications to boot also. well; while its back to updating my CV; I'd love to hear about your experiences on getting a job here."""</OrgQBody>

	<Thread THREAD_SEQUENCE="Q318_R14" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q261_R18">
		<RelQuestion RELQ_ID="Q318_R14" RELQ_RANKING_ORDER="14" RELQ_CATEGORY="Opportunities" RELQ_DATE="2011-01-11 14:32:27" RELQ_USERID="U5035" RELQ_USERNAME="aravind_nithila" RELQ_RELEVANCE2ORGQ="Relevant">
			<RelQSubject>About the job oppourtinites for Women in Doha</RelQSubject>
			<RelQBody>hi; How about the job oppourtinites are there in doha for women who had IT experience? with regards A.Aravind</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q318_R14_C1" RELC_DATE="2011-01-18 09:35:04" RELC_USERID="U5036" RELC_USERNAME="bhavani38" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Hi; Am also looking for the same topic. Can anybody tell me good jobs for Women with IT experience of 5-6 years?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R14_C2" RELC_DATE="2011-01-22 23:16:45" RELC_USERID="U5037" RELC_USERNAME="aatef" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>In my opinion who have IT qualification and experience are lucky :) there are lot of opportunities in many organisations ;like Banks ; Hospitals ; Schools ; it is IT dear :) try ; will find ; trust me ..</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R14_C3" RELC_DATE="2011-01-22 23:26:48" RELC_USERID="U5038" RELC_USERNAME="Hannah Montana" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>They are plenty of IT opportunities unless you are looking for in IT.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R14_C4" RELC_DATE="2011-02-03 20:01:33" RELC_USERID="U5039" RELC_USERNAME="wafamerai" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Hi; it's not true what you say; I am looking for a suitable job in IT since 8 months and I didn't find anything. I am an IT engineer with 3 years experience :(</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R14_C5" RELC_DATE="2011-02-03 20:29:02" RELC_USERID="U78" RELC_USERNAME="qatarisun" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>wafamerai; your problem is not your profession; but your nationality. no visas for Tunisian female; that's why companies don't conact you or don't send you the offers.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R14_C6" RELC_DATE="2011-02-04 01:22:29" RELC_USERID="U1060" RELC_USERNAME="anwarji" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>As per my experience in qatar....there are very few opportunities on IT from local companies and have more chances in foriegn companies but the problem to get the good chance recommondations.......hopefully.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R14_C7" RELC_DATE="2013-10-29 09:10:40" RELC_USERID="U5040" RELC_USERNAME="maryan" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Please the same thing applicable to me. A graduate in Secretarial Administration for some time now. from Nigeria with Husband's Company sponsorship Visa even in related field to no avail.To all listeners look in to it and subject for me on what to do because i really need help.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R14_C8" RELC_DATE="2013-10-29 09:21:48" RELC_USERID="U516" RELC_USERNAME="mast kalandar" RELC_RELEVANCE2ORGQ="Good" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Have patience and try Inshallah you are all deserving candidates to get a good job in IT</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R14_C9" RELC_DATE="2013-10-29 09:37:09" RELC_USERID="U66" RELC_USERNAME="Molten Metal" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Sister Maryan; Keep your hopes alive .... !</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R14_C10" RELC_DATE="2014-08-02 10:18:23" RELC_USERID="U5041" RELC_USERNAME="Sayantan" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Hi Arvind; I have the same question. Do you have any inputs for work opportunities of women in Qatar? thanks; Sayantan</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q318">
	<OrgQSubject>"IT Jobs in Qatar</OrgQSubject>
	<OrgQBody>""how hard is it for you to get a decent paying job in qatar? I had applied in bayt;monstergulf and gulftalent almost religiously every day and yet I am getting nothing more than having my CV viewed. I have 4 years + experience in Linux and Unix environment and a handful of certifications to boot also. well; while its back to updating my CV; I'd love to hear about your experiences on getting a job here."""</OrgQBody>

	<Thread THREAD_SEQUENCE="Q318_R17" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q215_R66">
		<RelQuestion RELQ_ID="Q318_R17" RELQ_RANKING_ORDER="17" RELQ_CATEGORY="Opportunities" RELQ_DATE="2013-09-06 22:34:19" RELQ_USERID="U4598" RELQ_USERNAME="samzuna" RELQ_RELEVANCE2ORGQ="Relevant">
			<RelQSubject>requirements to get a job in qatar police?</RelQSubject>
			<RelQBody>Hi everyone! I born &amp; raised in dubai; my nationality is pakistan. I am flent in arabic lang;.. I am on visit visa in qatar; is there any way to get selected in police; since im on visit? I will really appreciate ur kind comments..</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q318_R17_C1" RELC_DATE="2013-09-06 22:54:56" RELC_USERID="U956" RELC_USERNAME="Rip Cord" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I thought Pakistani cause most of the crimes not solve them?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R17_C2" RELC_DATE="2013-09-06 22:55:18" RELC_USERID="U2584" RELC_USERNAME="riaz_ak" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Try it. Depends on ur luck.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R17_C3" RELC_DATE="2013-09-06 23:02:38" RELC_USERID="U2485" RELC_USERNAME="Billaz Montana" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>my friend is also from pakistan ; he came here 1 year ago and doesnt know a single arabic word .. he is raised in pakistan he got a job in one of the best army job . he only goes for job 3 days a week . i dont know if its his luck or big wasta there is a place somewhere in doha ; you just have to visit and give your information ... dont know where it is</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R17_C4" RELC_DATE="2013-09-06 23:22:45" RELC_USERID="U4598" RELC_USERNAME="samzuna" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>by the way; were ur cousin on visit visa ?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R17_C5" RELC_DATE="2013-09-06 23:31:46" RELC_USERID="U4598" RELC_USERNAME="samzuna" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>man!! we r not that bad but our public image has been destroyed by the unknown terrorist organizations and media; by the way there r good n evil everywhere</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R17_C6" RELC_DATE="2013-09-06 23:42:19" RELC_USERID="U513" RELC_USERNAME="jungle_book" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>can you eat 5 afgan kuboose in 10 min? if yes; easy to get that job.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R17_C7" RELC_DATE="2013-09-07 00:00:29" RELC_USERID="U4599" RELC_USERNAME="gbs123" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>whoever is bad he think Pakistanis r bad; plz think positive</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R17_C8" RELC_DATE="2013-09-07 00:21:06" RELC_USERID="U4600" RELC_USERNAME="ali ok" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>lancer 2007 model sale 1.3 call 66136714</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R17_C9" RELC_DATE="2013-09-07 00:24:56" RELC_USERID="U4598" RELC_USERNAME="samzuna" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I thought my jokes were bad but ur's damn boring..; try another one and hopefully I might laugh</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R17_C10" RELC_DATE="2013-09-07 01:04:40" RELC_USERID="U4601" RELC_USERNAME="aiskaleem" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>RIP CORD; WHAT ARUBANS DO BY THE WAY IF MOST PAKISTANIS ARE CRIMINALS; DO U HAVE SOME PERSONAL ISSUES; OR SOME PAKISTANI COMMITTED A CRIME AGAINST YOU. AM SURE THERE WILL BE MORE CRIMINALS LIKE YOU IN ARUBA; THAT IS WHY YOU HAVE BEEN KICKED OUT.</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q318">
	<OrgQSubject>"IT Jobs in Qatar</OrgQSubject>
	<OrgQBody>""how hard is it for you to get a decent paying job in qatar? I had applied in bayt;monstergulf and gulftalent almost religiously every day and yet I am getting nothing more than having my CV viewed. I have 4 years + experience in Linux and Unix environment and a handful of certifications to boot also. well; while its back to updating my CV; I'd love to hear about your experiences on getting a job here."""</OrgQBody>

	<Thread THREAD_SEQUENCE="Q318_R19" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q75_R41">
		<RelQuestion RELQ_ID="Q318_R19" RELQ_RANKING_ORDER="19" RELQ_CATEGORY="Opportunities" RELQ_DATE="2008-03-02 00:29:44" RELQ_USERID="U2439" RELQ_USERNAME="esadbey" RELQ_RELEVANCE2ORGQ="Relevant">
			<RelQSubject>how to find a job?</RelQSubject>
			<RelQBody>hi i am new at this forum; so sorry if u were already speaking about this topic. i am planning to move to doha on the end of this year; together with husband. he is chef in the restaurant and we are wondering how to find jobs for both of us . I am speaking english ; arabic; greek and serbian; so maybe if it is possible something in the tourism. which web sites i should visit? thanx</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q318_R19_C1" RELC_DATE="2008-03-02 01:38:43" RELC_USERID="U2440" RELC_USERNAME="bulele08" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>try visiting www.bayt.com</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R19_C2" RELC_DATE="2008-03-02 06:34:17" RELC_USERID="U2441" RELC_USERNAME="Annel Ocampo" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Hi I am an accounting graduate with 9 years experience in my field and am looking for a job in Doha. Thanks</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R19_C3" RELC_DATE="2008-03-02 07:25:40" RELC_USERID="U14" RELC_USERNAME="irrysa" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>  Try hotels like marriott; ritz-carlton; sheraton; etc. Bayt.com is also good. you can also check the web site for the newspapers; like www.gulf-times.com and check their ads section. Sometimes the recruiting agencies are also advertising in that newspaper; so you can take some names from there as well. good luck!    If you're looking for a problem; you're probably gonna find one.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q318_R19_C4" RELC_DATE="2008-03-02 07:43:42" RELC_USERID="U78" RELC_USERNAME="qatarisun" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">